### ISSUE TITLE
problem while compiling smallUBPB with VS2012 64 bit, OpenEXR specific problem

### ISSUE THREAD

**Issue by Mohamed-Sakr** [PetrVevoda/smallupbp#1]
Hi,
    I was trying to compile the project, but there is a version mismatch between OpenEXR.lib and the current compiler binaries

in debug mode, example of error:
2>OpenEXR-dbg.lib(IexBaseExc.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1700' in Bre.obj

in release mode,
 2>LINK : fatal error C1047: The object or library file '../OpenEXR/OpenEXR.lib' was created with an older compiler than other objects; rebuild old objects and libraries

somehow I MUST compile OpenEXR.lib in VS2012 to overcome this problem, I tried to compile OpenEXR and  ilmbase, but OpenEXR,lib is not generated by anything??

here is the lib folder

Half.lib
Iex.lib
IlmImf.lib
IlmThread.lib
Imath.lib
zlibwapi.lib

I guess I can work around this by compiling with VS2010 compiler, but this won't be C++ 11 as stated in the recommendations

cheers,
Mohamed Sakr

**Comment by PetrVevoda** [comment]
Hello,

Thank you for reporting your problem.

You are right, OpenEXR.lib is not generated by anything. Please use VS2010 compiler, it actually supports all we need from C++ 11. When opening the solution file for the first time, do not let Visual Studio upgrade the projects.

I hope this will help.

Best regards,
Petr Vevoda

**Comment by PetrVevoda** [comment]
OpenEXR.lib is now generated by its own project and all projects use the Visual C++ 2013 compiler (see the README.txt file or the project page for updated compilation information).
